from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'watchlists'

# Declares a router to autogenerate REST endpoints for watchlists
# ModelViewSets.
router = routers.DefaultRouter()
# Registers the WatchListViewSet modelViewSet with the router with the
# base url 'watchlists' NOTE: the project itself uses the base 'api'
# so the base url is actually `api/watchlists/`.
router.register('watchlists', views.WatchListViewSet)

# urlpatterns registers end points
urlpatterns = [
    # Binds the autogenerated endpoints to the end point paths.
    path('', include(router.urls)),
]
