# Generated by Django 2.2.3 on 2019-07-29 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('view_count', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_owned_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-view_count',),
                'unique_together': {('name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='WatchListDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('watchlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_details', to='watchlists.WatchList')),
            ],
            options={
                'unique_together': {('watchlist_id', 'symbol')},
            },
        ),
    ]
